[tool.poetry]
name = "tabula-note-service"
version = "1.0.0"
description = "Note Service API for processing note data and providing guidelines"
packages = [
    { include = "note_service" }
]

[tool.poetry.dependencies]
python = "^3.11"
tabula-common-sdk = { path = "../../libs/common-sdk", develop = true }
tabula-note-sdk = { path = "../../libs/note-sdk", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

